version: "3.8"

services:
    multiagent:
        build: .
        ports:
            - "5000:5000"
        environment:
            - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
            - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
            - DEBUG=${DEBUG:-false}
            - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS:-10}
            - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-30}
            - LOG_LEVEL=${LOG_LEVEL:-INFO}
        restart: unless-stopped
        volumes:
            # Mount logs directory for persistence (optional)
            - ./logs:/app/logs
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5000/api/metrics"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        # Resource limits (optional)
        deploy:
            resources:
                limits:
                    memory: 1G
                    cpus: "1.0"
                reservations:
                    memory: 512M
                    cpus: "0.5"

# Optional: Add a reverse proxy for production
# nginx:
#   image: nginx:alpine
#   ports:
#     - "80:80"
#     - "443:443"
#   volumes:
#     - ./nginx.conf:/etc/nginx/nginx.conf
#   depends_on:
#     - multiagent
#   restart: unless-stopped

# No databases needed! 🎉
# This is the complete setup - just the app and optional nginx

networks:
    default:
        name: multiagent-network
